baseURL = "https://gh.shoogle.net/ghana"
languageCode = "en"
title = "Ghana"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "ghana"

[taxonomies]
  shop = "shops"

